<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * CronRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronRepository extends \Doctrine\ORM\EntityRepository
{
    public function findShops()
    {

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('AppBundle:Shop', 's');
        $rsm->addFieldResult('s', 'id', 'id');
        $rsm->addFieldResult('s', 'name', 'name');
        $rsm->addFieldResult('s', 'api_url', 'apiUrl');
        $rsm->addFieldResult('s', 'repeat_time', 'repeatTime');
        $rsm->addFieldResult('s', 'responce_type', 'responceType');
        $rsm->addFieldResult('s', 'responce_raw', 'responceRaw');
        $query = $this->getEntityManager()->createNativeQuery('
            SELECT *
            FROM shop s
            WHERE s.repeat_time +
                  ( SELECT cron.created_at
                    FROM cron
                    WHERE cron.shop_id = s.id
                    ORDER BY cron.created_at DESC
                    LIMIT 1
                  ) < ?
            GROUP BY s.id',
            $rsm
        );
        $query->setParameter(1, time());

        return $query->getResult();
    }
}
