<?php

namespace AppBundle\Entity\Repository;

/**
 * FieldMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldMapRepository extends \Doctrine\ORM\EntityRepository
{
}
