<?php

namespace AppBundle\Entity\Repository;

/**
 * ShopConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
